services:
    _defaults:
        autowire: true
        autoconfigure: true

    Dwo\UserCommandsBundle\:
        resource: '../../*'
        exclude: '../../{Command,DependencyInjection,Resources,Tests}'

    Dwo\UserCommandsBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']
